services:
  # Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: refly_db
    restart: always
    environment:
      POSTGRES_DB: refly
      POSTGRES_USER: refly
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-refly_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U refly']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - refly_network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: refly_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-refly_redis_password}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--no-auth-warning', '-a', '${REDIS_PASSWORD:-refly_redis_password}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - refly_network

  # MinIO para almacenamiento de archivos
  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: refly_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - refly_network

  # Qdrant para búsqueda vectorial
  qdrant:
    image: qdrant/qdrant:v1.13.1
    container_name: refly_qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ['CMD-SHELL', "curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - refly_network

  # SearXNG para búsqueda web
  searxng:
    image: searxng/searxng:latest
    container_name: refly_searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=https://${DOMAIN:-localhost}/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    networks:
      - refly_network

  # API Backend
  api:
    image: reflyai/refly-api:latest
    container_name: refly_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      # Base de datos
      DATABASE_URL: postgresql://refly:${POSTGRES_PASSWORD:-refly_secure_password}@db:5432/refly?schema=refly
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-refly_redis_password}
      
      # MinIO
      MINIO_INTERNAL_ENDPOINT: minio
      MINIO_INTERNAL_PORT: 9000
      MINIO_INTERNAL_USE_SSL: 'false'
      MINIO_INTERNAL_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_INTERNAL_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_INTERNAL_BUCKET: refly-internal
      MINIO_EXTERNAL_ENDPOINT: minio
      MINIO_EXTERNAL_PORT: 9000
      MINIO_EXTERNAL_USE_SSL: 'false'
      MINIO_EXTERNAL_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_EXTERNAL_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_EXTERNAL_BUCKET: refly-external
      
      # Qdrant
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_API_KEY: ''
      REFLY_VEC_DIM: 768
      
      # SearXNG
      SEARXNG_BASE_URL: http://searxng:8080
      
      # JWT y autenticación
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_change_this}
      JWT_EXPIRATION_TIME: 6h
      JWT_REFRESH_EXPIRATION_TIME: 7d
      AUTH_SKIP_VERIFICATION: 'true'
      
      # APIs requeridas (DEBES configurar estas variables)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: https://api.openai.com
      
      # APIs opcionales
      JINA_API_KEY: ${JINA_API_KEY:-}
      SERPER_API_KEY: ${SERPER_API_KEY:-}
      
      # Configuración de embeddings
      EMBEDDINGS_PROVIDER: jina
      EMBEDDINGS_MODEL_NAME: jina-embeddings-v3
      EMBEDDINGS_DIMENSIONS: 768
      
      # Configuración general
      NODE_ENV: production
      PORT: 5800
      WS_PORT: 5801
      ORIGIN: https://${DOMAIN:-localhost}
      
      # Endpoints estáticos
      STATIC_PUBLIC_ENDPOINT: /api/v1/misc/public
      STATIC_PRIVATE_ENDPOINT: /api/v1/misc
      
      # Configuración adicional
      COLLAB_TOKEN_EXPIRY: 12h
      PARSER_PDF: pdfjs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5800/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - refly_network

  # Frontend Web
  web:
    image: reflyai/refly-web:latest
    container_name: refly_web
    restart: always
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      API_URL: /api
      COLLAB_URL: /collab
      STATIC_PUBLIC_ENDPOINT: /api/v1/misc/public
      STATIC_PRIVATE_ENDPOINT: /api/v1/misc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - refly_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  refly_network:
    driver: bridge
